name: Hector Zarate. iOS Cowboy.
gems: [jekyll-paginate]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
timezone: Europe/Berlin
paginate: 4
paginate_path: "blog/page:num"
future: true

analytics:
  provider: google
  google:
    tracking_id: 'UA-46675146-1'
