name: Hector Zarate. iOS Cowboy.
markdown: redcarpet 
timezone: Europe/Berlin
paginate: 4
paginate_path: "blog/page:num"
future: true

analytics:
  provider: google
  google:
    tracking_id: 'UA-46675146-1'
